### ISSUE TITLE
Conversion from old data base

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#13]
## The Problem

The option to Convert from MS Access data base yielded river miles with odd and excessive decimal points.

## Reproduction steps

Convert a data base.  
Go to Data | Surveys.

![xs](https://user-images.githubusercontent.com/41058803/44741609-1e78bb80-aaed-11e8-9998-c157ade7a592.jpg)

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
@JohnShelley this is an easy fix. The values in the database are now stored with full precision, but we have worked hard to always show them as rounded values. We obviously missed one of the places! Let me know if you see other places in the software.

**Comment by philipbaileynar** [comment]
Fixed via #21
