### ISSUE TITLE
Incorrectly including single intersection "defined stations" in the "within" and "without" options

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#14]
## The Problem
The previous XSViewer could tell if a defined station had one or two intersects per transect, and so it didn't include the "sailing line".  The new XSViewer incorrectly includes the sailing line.

![sailingline](https://user-images.githubusercontent.com/41058803/44741863-eaea6100-aaed-11e8-9503-7caf789cfea1.jpg)

**Comment by JohnShelley** [comment]
And it crashes if that option is selected then "Update Plot" is selected.

**Comment by philipbaileynar** [comment]
@JohnShelley this is indeed a bug and it is super easy to fix.

**Comment by philipbaileynar** [comment]
This is fixed for the next release.
