### ISSUE TITLE
Error when opening a new data base from the surveys screen

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#17]
## The Problem

I tried to open a new data base while the "Surveys" screen was open.  It threw an error that said, "Handled Exception."  After hitting close, it opened up a file dialog as expected and worked fine.

test exception
 --- Exception Data --- 
Cross Section Viewer = 2.0.11.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 8/28/2018 1:32:53 PM

**Comment by philipbaileynar** [comment]
This was a legacy piece of code to help debug how to launch the Cross Section Viewer by double clicking on a database directly in Windows Explorer.

I've removed the line of code. This issue will be fixed in the next version!
