### ISSUE TITLE
Extra column in the template

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#23]
## The Problem

Created an empty survey template includes a column named "StationIndex" that was never there before.

![2018-09-12 14_22_41-access - testtemplate _ database- c__users_g5edhjs9_documents_telework_test_test](https://user-images.githubusercontent.com/41058803/45448270-68eb6200-b6c1-11e8-8968-48f0b7c116e3.png)

**Comment by JohnShelley** [comment]
If this is now needed... what is it and what should be put there?

**Comment by philipbaileynar** [comment]
Yes, this is the field that tells the software how to order survey points along a transect. It is an integer field that must be unique for each survey point along a surveyed transect. It can start at any value, but typically the values would start at 1 and increment by 1 for each survey point.

**Comment by philipbaileynar** [comment]
Asked and answered.
