### ISSUE TITLE
Access Converter Breaks with multiple measurements of XS in the same survey

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/xsviewer-issues#33]
Originally reported as part of #29 this issue is actually a distinct problem with the data in some older cross section databases. The following error message was received by both @JohnShelley and Gene Spangrude using the same **Kansas River** database.

![2019_07_29_155409](https://user-images.githubusercontent.com/8645379/62088143-266b3f00-b219-11e9-8471-fb2b6ac38748.png)

The problem is that version 1 of the Cross Section Viewer software allowed a single survey to capture the same cross section multiple times. In the Kansas River database that produced this error there are five cross sections that are captured twice during a particular survey. I don't know if this is an error or by design.

![2019_07_29_155007](https://user-images.githubusercontent.com/8645379/62088051-cbd1e300-b218-11e9-8e9b-30cc1a0fd3c8.png)

Version 2 of the software is more restrictive and only allows a single copy of a cross section within each survey.

The problem with allowing multiple cross sections in a single survey is that there's no way for the longitudinal tools to determine which version of the cross section to use during calculations.

How should we proceed:

1. Allow multiple representations of a single cross section within each survey.
2. Implement a warning in the converter that tells the user to separate their data into separate surveys before attempting to convert the data.

**Comment by JohnShelley** [comment]
Philip,

I think we just need a more descriptive error and for those of us with problems like that in the database to know how to remove the duplicates.

Allowing multiples of the same cross section in the same survey is not needed.

-John

**Comment by philipbaileynar** [comment]
Here is the new online help section that shows the more specific warning message as well as describing two solutions.

http://xsviewer.northarrowresearch.com/Online_Help/File_Menu/convert_database.html#duplicate-cross-sections
