### ISSUE TITLE
Incorrect Order of Cross Sections in Selection

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/xsviewer-issues#54]
Reported by @JohnShelley via email on 1 Apr 2020:

When I create a selection from RM 0 to 500, I get a list of RM that are not in order.  It appears they are in order for one survey, then they start over in order for the next survey.  The resulting list is therefore not sorted, which is not a helpful way to scroll through cross sections in the Plot Cross Sections tool.

![xs1](https://user-images.githubusercontent.com/8645379/78590319-84174880-77f6-11ea-8604-fc8f6cd848fe.jpg)
![xs2](https://user-images.githubusercontent.com/8645379/78590325-85487580-77f6-11ea-93f4-b879b11b9850.jpg)

**Comment by GeneSpangrude** [comment]
I have noticed this item too; I believe its related to not all 'Surveys' containing 'all Sections' or some 'Surveys' containing additional sections.....  at least that is one thing I noticed in my situation......

**Comment by philipbaileynar** [comment]
@JohnShelley also reported this on 22 July 2020:

![image](https://user-images.githubusercontent.com/8645379/88566354-bdb0d100-cfea-11ea-8677-206cb92125f4.png)

**Comment by philipbaileynar** [comment]
This was resolved in 3.1.15
