### ISSUE TITLE
Surface Area Tool Binning Error

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/xsviewer-issues#68]
*Reported by John Shelley on 13 Se p2021*

By the way, in the surface area tool, notice how the first bin only goes to 5, even though the increment is 10.  For some reason, the first bin is always half the increment.

![image001](https://user-images.githubusercontent.com/8645379/133296584-8703a2b2-8b16-4dee-a470-036593fea207.jpeg)

I think the first bin should go 0 to whatever the depth increment is.  And so on until the last bin.  And the last bin might not include a full 10 miles (in this case) if the greatest depth is greater than 35, then there should be another bin that says “>35” or else it should go “35 - <max>” with “max” being the maximum depth rounded up to the nearest foot (39 or whatever it is for this data set).

I think now those deeper depths are just not being included?

**Comment by philipbaileynar** [comment]
I can confirm that the underlying calculation is correct. It is calculating values at the midpoint of each bin. Therefore, the problem seems to be the labeling of the bins is incorrect.

<img width="730" alt="Screen Shot 2021-09-14 at 10 14 19 AM" src="https://user-images.githubusercontent.com/8645379/133303406-4cab4653-e975-4211-b49a-b11efabae737.png">

**Comment by MattReimer** [comment]
@philipbaileynar make sure if it's appropriate that any fixes and/or changes get corresponding tickets in 

https://github.com/NorthArrowResearch/xsonline-monorepo

Just so that we don't have to both discover and fix bugs in two places.

**Comment by philipbaileynar** [comment]
This is fixed in 4.0.1. The data were being calculated correctly but display bin labels were not being created using the proper values. This is now fixed.
