### ISSUE TITLE
Long Profile Viewer- Reference Plane Relative to Reference Plane

### ISSUE THREAD

**Issue by JohnShelley** [NorthArrowResearch/xsviewer-issues#8]
## The Problem

The long profile viewer incorrectly displays reference planes when "Relative to a reference plan" is selected.  Also, "plan" should be "plane" .

## Reproduction steps

1. Select a reference plane to display.
2. Select a long profile to display.
3. Select the "Relative to reference plan" button.

## Exception message

The long profile plots correctly relative to a reference plane.  But the other reference planes do not plot correctly in "relative to a reference plane" mode.

![longprofilerefplane](https://user-images.githubusercontent.com/41058803/42509891-ce6f65c0-843c-11e8-95bd-8374debc2703.png)

The reference planes should also plot relative to the selected reference plane.

```

**Comment by philipbaileynar** [comment]
Are you referring to the red line and the fact that it is not flat? 

This is actually the same behaviour as the previous version of the software. We always intended that it wasn't that helpful to display any reference planes when using the the "relative to reference" feature. Therefore we simply relied on the user unchecking the box next to all the reference planes.

Options:

1. If users genuinely need to see the difference between two reference planes (i.e. check one reference plane in the listbox and show it relative to another reference plane using the "relative to reference plane" feature) then we can certainly do this. If so we can update the tool to show all data series relative to whatever is selected as the "relative" reference plane.
1. Only show the reference plane data series on the plot when using the "absolute" mode.

Please confirm which option is preferable.

**Comment by JohnShelley** [comment]
CLASSIFICATION: UNCLASSIFIED

Option 1.
-John

-----Original Message-----

**Comment by philipbaileynar** [comment]
Implemented for version 2.0.9
